name: Context var demo
on: workflow_dispatch
jobs:
  context_var:
    runs-on: ubuntu-latest
    steps:
      - name: use contaxt variables
        run: |
          echo "This workflow is triggered by ${{github.actor}}"
          echo "The repository name is ${{github.repository}}"
          echo "The branch is ${{github.ref_name}}"
          
      - name: print all variables under github
        run: echo "${{toJson(github)}}"
