name: Inputs Demo
on:
  workflow_dispatch:
    inputs:
      environmet:
        description: Choose the env to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod
      artifact_tag:
        description: choose artifact to deploy
        required: true
jobs:
  inputs_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        run: echo "Deploy the application with ${{inputs.artifact_tag}} to ${{inputs.environmet}}"
